### PR TITLE
set Fasta(rebuild=False)

### PR DESCRIPTION
**Pull request by DongzeHE**

### CODE REVIEW

**Comment by panushri25** [comment]
@DongzeHE instead of changing the main code, I recommend that you have a seperate script to reformat your peaks to the required format.

**Review by panushri25 — COMMENTED** [review]
@DongzeHE instead of changing the main code, I recommend that you have a separate script to reformat your peaks to the required format.

Its not standard to have the comment lines in peak files. And this can change with software. So I will not include this as of now.

**Review by panushri25 — COMMENTED** [review]
Can you send another PR with only these changes?

**Comment by DongzeHE** [comment]
Hi @panushri25,

> Can you send another PR with only these changes?

I could not see what are the changes you referred to. Are we talking about the first commit or the second?

> Its not standard to have the comment lines in peak files. And this can change with software. So I will not include this as of now.

I am not sure if I agree with you on this point. As a valid BED file, it is totally possible that there are header lines in the peak files starting with a `#` and I have tested that having header lines made ChromBPNet crash because pandas loaded all the integers as floats for some reason if having nan values, which made python unhappy when indexing strings/arrays using floats. 

Of course all above are just my suggestions. You decide what to do for your tool ;P Just lemme know what do you want me to do for this PR. 

Thanks,
Dongze

**Comment by panushri25** [comment]
Haha dont worry about the PR, I will incorporate the possible suggestions in the next version. 

I think we will eventually integrate the tool to call peaks from input frags and bams, so standardizing peak files is no longer an issue. Thanks for all your suggestions.

**Pull request closed without merging**
