### PR TITLE
adding pseudocount to prevent div by 0 error

### PR DESCRIPTION
**Pull request by annashcherbina**
getting div by 0 error in metrics.py , need to add pseudocount to prevent this.

### CODE REVIEW

**Review by amanpatel101 — APPROVED** [review]
Looks good.

**Review by kmualim — APPROVED** [review]
Looks good!

**Comment by panushri25** [comment]
@annashcherbina I was looking deeper into this issue. This bug should actually not occur because we are filtering out regions with zero reads in both step6_train_chrombpnet_model.sh and step4_train_bias_model.sh and running the prediction scripts on the filtered bed. Do you know why this error is happening for you?  How are you using this predict.py and metrics.py script?

**Comment by annashcherbina** [comment]
Hi @panushri25 , thanks for looking at it. 
I have copied the input data, refs, and run scripts (run3.sh ... run6.sh) to this folder: 
`/oak/stanford/groups/akundaje/projects/chrombpnet/debug/` let me know if anything else would be useful to provide?

**Pull request merged**
