### PR TITLE
Preprocessing

### PR DESCRIPTION
**Pull request by panushri25**
Hello :)

I would like your feedback on the scripts in the following folders - src/utils/preprocessing/ and src/utils/preprocessing/analysis
Feedback on the following fronts would be helpful 

(1) Is the README comprehensive? Any typos, anything missing? Does this help you run the scripts/codes smoothly?
(2) Are scripts documented well?
(3) Can you test it on a dataset of your choice and let me know if it works and giving results as expected?

Thank you,
Anu

### CODE REVIEW

**Comment by ziwei-75** [comment]
I think the documentation is great. I tested bam_to_bigwig.sh and build_pwm_from_bigwig.py. They work as expected. The documentation is pretty clear. The only thing I would suggest is add an example of how you use it. For instance, `python build_pwm_from_bigwig.py --bigwig=/oak/stanford/groups/akundaje/ziwei75/T2D_MPRA/data/processed/hesam_2021/AMSC_D2.bw --genome=/mnt/lab_data3/ziwei75/T2D_MPRA/data/processed/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta --output_prefix=./test_AMSC_D2 --chr=chr1 --chr_size=248956422 `
Usually I put --chr=1 and chr-size as the path to the hg38.chromo.sizes. But here is different. Otherwise, I think running the script is pretty smooth.

**Comment by akundaje** [comment]
Yes I agree pointing to a chr.sizes file rather than providing a number
explicitly.

-A

**Comment by panushri25** [comment]
Got it thank you, will resolve that!

**Comment by panushri25** [comment]
@ziwei-75 Made all the changes you suggested
(1) add chrom_sizes file as input instead of manual input of size
(2) Made unfiltered/filtered usage in bold
(3) Added hyperlink to discussion to clarify the difference in PE/SE filtering
(4) Added example usage in all scripts.

What do you think?

**Comment by ziwei-75** [comment]
I think it looks great! Thanks for making those documentations. I am pretty familiar with those scripts, so we should also have some new users to review the documentation.

**Comment by panushri25** [comment]
@akshat998 in case its confusing here is the link - https://github.com/kundajelab/chrombpnet/tree/preprocessing/src/utils/preprocessing

**Comment by panushri25** [comment]
Note to self - need to change pysam to pyfaidx to load fasta files - for consistency

**Comment by panushri25** [comment]
Note to self - (1) add pwm check and abort further run if this check fails (2)  add support to do bigwig generation from fragments

**Comment by akshat998** [comment]
Hello, 
Just a few thoughts while running `bam_to_bigwig.sh`: 
1. When running on the group cluster, I used module load `ucsc_tools`. It would be nice to add this into the README. Without this being mentioned, a new user might think that they are responsible for installing `samtools` & `bedGraphToBigWig`. 
2. Is it valuable to have this running on a completely new machine for an external user? I tried installing `samtools` & `bedGraphToBigWig` on my laptop but was unable to run the script successfully. If so, some instructions for running the script for  a new user would be valuable 
Hope this helps!

**Comment by akundaje** [comment]
Agree. All tools should be installed automatically as part of the docker
image or whatever other image is being used. Don't assume anything
installed and have strong control of exact versions etc.

**Comment by panushri25** [comment]
Thanks for the suggestions Akshat!

(1) Regarding using - module load `ucsc_tools` . This option works only for Kundaje lab members, I dont know including this might be helpful for external users. 

(2) Docker image is a good option. This is a part of the to do and will get to this in due time - and test this on a machine where there are no installations setup.

**Comment by panushri25** [comment]
Hello, I am going to merge these changes into the main repo to release an updated chrombpnet version - feel free to open this thread if you have any feedback

**Comment by panushri25** [comment]
I already made a todo of the feedback received here - https://github.com/kundajelab/chrombpnet/wiki

Let me know if there is more, thank you! :)

**Pull request merged**
