### PR TITLE
generate installable package for chrombpnet that corresponds to pypi release 0.1

### PR DESCRIPTION
**Pull request by annashcherbina**
PyPi release 0.1 generated: https://pypi.org/manage/project/chrombpnet/releases/

Created MIT license, setup.py file with entrypoint scripts for installation.

### CODE REVIEW

**Comment by annashcherbina** [comment]
Note: I used updated modisco version (from PR https://github.com/kundajelab/chrombpnet/pull/25) to generate pypi release. 

Also AvantiShri shap is obsolete, replaced by kundajelab/shap, and it's good to specify the branch (master) we want to use for the dependency.

**Comment by austintwang** [comment]
Hi, thanks for doing all of this!

Are the `console_scripts` here drop-in replacements for the original chrombpnet scripts?
https://github.com/kundajelab/chrombpnet/blob/45b6bbdca3c27a432b808724d7e242a5454082dc/setup.py#L29-L35

**Comment by annashcherbina** [comment]
> Hi, thanks for doing all of this!
> 
> Are the `console_scripts` here drop-in replacements for the original chrombpnet scripts?
> 
> https://github.com/kundajelab/chrombpnet/blob/45b6bbdca3c27a432b808724d7e242a5454082dc/setup.py#L29-L35

console scripts just call the main functions for training/predictions/etc -- these are the python functions that get invoked in steps 3 - 7 in the example shell scripts provided in the repo. They are a convenience metric so the user can call the script directly from the command line.

**Comment by austintwang** [comment]
One issue is that the shell scripts expect the user to be in same working directory as the script, which is problematic when stuff's installed through pip. I don't really know the best solution to this, apart from rewriting everything in python.

What I ended up doing in my private branch was to force package installation into the filesystem:
https://github.com/kundajelab/chrombpnet/blob/7a4959dc2d0790369ec181d05821c56064a58188/setup.cfg#L8

... and then create a wrapper python script around the shell scripts that converts all input paths to absolute paths, and set the working directory as the installed package root directory:
https://github.com/kundajelab/chrombpnet/blob/austin/src/chrombpnet/cmdline.py
https://github.com/kundajelab/chrombpnet/blob/7a4959dc2d0790369ec181d05821c56064a58188/src/chrombpnet/__init__.py#L3

... and set the script as a package entry point 
https://github.com/kundajelab/chrombpnet/blob/7a4959dc2d0790369ec181d05821c56064a58188/setup.cfg#L35-L37

However, these changes in my branch shuffle around files which could break people's workflows, which is why I'm hesitant to merge them.

**Comment by annashcherbina** [comment]
> 

I want to undertand what you mean by shell scripts expect the user to be in same working directory as the script -- 

console scripts simply read the package structure, and there shouldn't be a dependency on the folder where they are executed.  Just to clarify, calling `chrombpnet_train` is just a shortcut for calling `python chrombpnet/chrompbnet/training/train.py`, it is not itself replacing the full functionality of the shell script. The benefit is that the user doesn't need to know about package structure of chrombpnet to call "chrombpnet_train". 

I think the concern is the relative imports of submodules within chrombpnet package itself, right? Best practice would be to replace imports like 

```
import utils.argmanager as argmanager
import utils.losses as losses
import utils.callbacks as callbacks
``` 
with package-path: 

```
import chrombpnet.training.utils.argmanager as argmanager
import chrombpnet.training.utils.losses as losses
import chrombpnet.training.utils.callbacks as callbacks
```

I believe this gets around issue you mention @austintwang ? 
I'll make those updates in the PR, as it's helpful to have the path for readability too I think? Let me know if you meant something different here?

**Comment by austintwang** [comment]
Just to clarify, I'm referring specifically to the bash scripts, either the main ones or the ones in the subdirectories. (I think the python files look great.)

For example, `step2_make_bigwigs_from_bams.sh` assumes `$PWD` is the directory containing the chrombpnet code, but the location might not be obvious if I install through pip.

**Comment by annashcherbina** [comment]
yup, that makes sense -- console scripts are meant to get around that issue -- if you install with pip, the console script "knows" where code lives. lemme finish the local --> global import change and I'll send an example maybe to help illustrate how I see this working and you can let me know if it addresses the concern? Will be helpful to have a concrete example to discuss.

**Comment by austintwang** [comment]
Sounds good, no rush! I understand how console scripts address the issue, but from my understanding, the ones in the repo don't currently contain all the functionality the existing bash scripts have. 

Totally fine, if that's the case-- I'm happy to help integrate more stuff as needed.

**Comment by panushri25** [comment]
Hi @austintwang and @annashcherbina ,

Thank you both for working on this! I will be sure to check this PR soon. Couple of things I wanted to communicate from my end -

(1) We are not ready to make a stable release yet. I am myself working on some changes and testing them out. I will push these changes in a couple of days. But I don't see the file structure changing much - so I think this PR can still be merged in after making these changes.
(2) This PR if not tested properly can break peoples workflows. So if you happen to work on it or review it - Can you make a note here on how you tested it? And discuss in detail the test cases and attach them here.

**Comment by annashcherbina** [comment]
@panushri25 sure that sounds good. 
We are not making an official release yet, are you ok with it going on the test pypi? 
https://test.pypi.org/
i.e. this is not a "real" release, it's meant to test the packaging and submodule imports .

**Comment by panushri25** [comment]
@annashcherbina Is https://test.pypi.org/ purely for testing purposes? When we are ready to merge these changes in and make "real" release for all the user we can move back to the pypi.org?

**Comment by annashcherbina** [comment]
> @annashcherbina Is https://test.pypi.org/ purely for testing purposes? When we are ready to merge these changes in and make "real" release for all the user we can move back to the pypi.org?

yes, testpypi is just for testing purposes -- it's not an actual package users can install. ie. to make sure we got the package structure right with relative imports of modules. This is hard to test with `pip install -e` as that won't capture the tests of the wheel object that gets generated with twine upon release.

**Comment by panushri25** [comment]
yeah https://test.pypi.org/  sounds fine for testing

**Comment by annashcherbina** [comment]
@austintwang -- I put in the changes that I think address the concern -- the scripts have been added in setup.py to scripts folder and PWD-specificity should be removed. Also added some checksk on missing arguments in the steps{n}*sh scripts. 
I'm going to test this out on some models I need to train and will confirm bug-freed-ness with these changes after work today. 

Have a look and let me know if these modifications sound reasonable?

**Comment by austintwang** [comment]
Sounds good, thanks! 

We should probably specify `zip_safe=False` in setup.py, to ensure that the package is installed into the filesystem and not as a zip file

**Comment by austintwang** [comment]
Added a `chrombpnet_srcdir` command that prints out the path of the installed package
Could help with any remaining edge cases for working-directory-specificity

**Comment by panushri25** [comment]
Hello @annashcherbina 

I got a notification that one of the commits is pertaining to an updated tensorflow version. I have heard from several people that the latest once breaks breaks because of memory issues. I need find out what these specific versions are. Will get back about this. Let me know if you know anything about this.

**Comment by annashcherbina** [comment]
@panushri25 -- I have been running workflows with the following settings without issue: 

tensorflow-gpu==2.8.0
tensorflow-estimator==2.8.0
tensorflow-probability==0.15.0


We would need to upgrade to at least tf 2.5 because 2.4 is no longer provided by the updated versions of pip, so probaby makes sense to upgrade to latest stable tf (2.8) since we must upgrade anyway. I can look into memory issues -- can you provide some examples of what's happening for debugging?

**Comment by ziwei-75** [comment]
I had a memory issue with TF2.6.0 when using chrombpnet-lite. So I tested the chrombpnet repo with TF 2.8.0 using the following packages: 
tensorflow-gpu==2.8.0
tensorflow-estimator==2.8.0
tensorflow-probability==0.15.0
numpy==1.20
TF 2.8.0 works fine for chrombpnet. No issues were observed during training.

**Comment by annashcherbina** [comment]
Excellent! Thanks for testing it @ziwei-75

**Comment by panushri25** [comment]
@annashcherbina can you do the typos in a separate PR and use this PR only for packaging specific things

**Comment by annashcherbina** [comment]
bugs need to be fixed to test the packaging, so they are blockers for this PR.

**Comment by annashcherbina** [comment]
i.e. console scripts will error out without the bug fixes in place 
console scripts need to be tested for packaging purposes

**Comment by panushri25** [comment]
okay never mind i will pick the typos/bugs independently then and do the remaining PRs in the weekend - the packaging PR will be merged only after a while - just a heads up

**Comment by annashcherbina** [comment]
Where there is no direct dependency between bug fix and packaging, I am making separate PR's, see here: 
https://github.com/kundajelab/chrombpnet/pull/31

I can create a parallel stream of PR's for just the bug fixes, sure. This PR is meant to produce a final, clean packageable version with unit tests to check for error-free completion. Unit tests will fail without the fixes, hence I'm adding them in this branch.

**Comment by annashcherbina** [comment]
@panushri25 @austintwang just a heads up that the packaging has been tested with this test: 

https://github.com/kundajelab/chrombpnet/commit/3fa0d128e1c1ed91cd364c4eb626fbe921cf4981 

So there is a full workflow running steps 1 - 7 with the package setup (i.e. without dependency on directory structures) (including auxiliary steps like generating gc background). We can executed this in CI/CD dockerized test when we launch new release to make sure all runs start to finish without issue.

**Pull request merged**
