### PR TITLE
directory-structure agnostic fix for step6

### PR DESCRIPTION
**Pull request by annashcherbina**
avoids the need to self-reference directory structure, which is quite bug prone and unreliable if package is installed w/ pip vs setup.py

### CODE REVIEW

**Comment by panushri25** [comment]
@soumyakundu What's the error that you are currently experiencing with this?

**Comment by panushri25** [comment]
The fix suggested will have some issues like the `mo` motif arguments need to be present in the `motifs_to_pwm.tsv` file. 

And the problem why this script breaks is because of these lines

```
srcdir=`chrombpnet_srcdir`
# marginal_footprint_dir=`echo which chrombpnet_marginal_footprints`
marginal_footprint_dir="$srcdir/evaluation/marginal_footprints"
```

I think @soumyakundu you might be getting and error that `chrombpnet_srcdir` does not exist?

**Comment by annashcherbina** [comment]
copying from slack: 

the problem is this : `srcdir=`chrombpnet_srcdir`
If installed from a wheel, this will just reference an egg file.
If installed from a tar distro, it will reference a path in conda
if installed via setup.py , it will reference the right path.
That is not really reliable.
To your point, we want to provide an option to use a different file, so we add an argument $pwm_f, that the user can provide to the script. If the user chooses not to provide that file, we populate a file with defaults for them, that is what’s done here:
```
#path to pwm file
if [ -z "$pwm_f" ]
  then
      echo "No pwm file supplied, using default"
      tee -a motif_to_pwm.default.tsv <<EOF 
tn5_1 	GCACAGTACAGAGCTG
tn5_2	GTGCACAGTTCTAGAGTGTGCAG
tn5_3	CCTCTACACTGTGCAGAA
tn5_4	GCACAGTTCTAGACTGTGCAG
tn5_5	CTGCACAGTGTAGAGTTGTGC
dnase_1	TTTACAAGTCCA
dnase_2	TGTACTTACGAA
NRF1	GCGCATGCGC
AP1	CGATATGACTCATCCC
CTCF	TTGGCCACTAGGGGGCGCTAT
ETS	CCGAAAGCGGAAGTGAGAC 
SP1	AAGGGGGCGGGGCCTAA
RUNX	CCCTAACCACAGCCC
NFKB	GCAAGGGAAATTCCCCAGG
GATA+TAL	GGCTGGGGGGGGCAGATAAGGCC
TAL	GGCTGGG
NFYB	CCAGCCAATCAGAGC
GABPA	GAAACCGGAAGTGGCC
BACH1+MAFK	AACTGCTGAGTCATCCCG
NRF1	CCCCGCGCATGCGCAGTGC
HNF4G	CCGTTGGACTTTGGACCCTG
EOF
      pwm_f=motif_to_pwm.default.tsv
fi
```
If the user provides their own file, with different motif names than tn5_1… , then their file will be used insteaad

**Comment by annashcherbina** [comment]
> 

chrombpnet_srcdir will vary depending on mode of installation, we should not rely on that to point to the git file structure

**Comment by annashcherbina** [comment]
The fix suggested will have some issues like the mo motif arguments need to be present in the motifs_to_pwm.tsv file.

^ My understanding is that this a desirable property? Can we parse these from col 1 in the input motif-to-pwm file? Rather than use separate argument I mean?

**Comment by panushri25** [comment]
okay if that is the case,  Can we  get rid of `-mo` argument altogether and the marginal_footprinting.py script should loop through all the motifs in either the default or `motis_to_pwm.tsv` input by the user.

**Comment by panushri25** [comment]
It doesn't make sense to  give default/optional input for one and hardcode the other dependent parameter.

**Comment by panushri25** [comment]
@annashcherbina Does this make sense ?

**Comment by annashcherbina** [comment]
Yes, for sure,  I like this idea (just read motif names from either default or col 1 of supplied file, will add that to the PR)

**Comment by panushri25** [comment]
Thank you!

Also need to update the readme here accordingly -  https://github.com/kundajelab/chrombpnet/tree/master/chrombpnet/evaluation/marginal_footprints

**Comment by annashcherbina** [comment]
Hey @soumyakundu -- Anusri mentioned that pwm footprinting did not run for you -- can you please specify the exact command you executed w/ inputs that were provided? Thanks! 

Based on the timestamps of your output files (http://mitra.stanford.edu/kundaje/soumyak/aav-design/data/chrombpnet_models/pv7_fold0/) it looks like you might have been using an old version of the code? Your outputs are timestamped 08/29, whereas this branch was updated after that.

**Review by panushri25 — APPROVED** [review]

**Comment by panushri25** [comment]
Will re-open if Aman's testing run fails

**Pull request merged**
